module.exports = {
  MIA: "MIA",
  MAX: "MAX",
  BEN: "BEN",
  AVA: "AVA",

  STORAGE_PLANET_COUNTER: "PLANETS",

  SCENE_KEY_START: 0,
  SCENE_KEY_SELECT_CHARACTER: 1,
  SCENE_KEY_WORLD: 2,
  SCENE_KEY_BATTLE_START: 3,
  SCENE_KEY_BATTLE_INTERLUDE: 4,
  SCENE_KEY_BATTLE: 5,
};
